// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmwuQ5nNxI4zd1DJyWA9Sg6itoKCMOl2A',
    appId: '1:561429560272:web:2c9dda65d0ad1b2cc357d5',
    messagingSenderId: '561429560272',
    projectId: 'habbit-f077c',
    authDomain: 'habbit-f077c.firebaseapp.com',
    databaseURL: 'https://habbit-f077c-default-rtdb.firebaseio.com',
    storageBucket: 'habbit-f077c.appspot.com',
    measurementId: 'G-ESVLL5EJD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKZ9w5TA2X7YPxq4bi9VBto46dg-l8Dsk',
    appId: '1:561429560272:android:e43b5bdf999d07d5c357d5',
    messagingSenderId: '561429560272',
    projectId: 'habbit-f077c',
    databaseURL: 'https://habbit-f077c-default-rtdb.firebaseio.com',
    storageBucket: 'habbit-f077c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUu6cDzGEJT3ore2kk75tLZaVW7cFDtjE',
    appId: '1:561429560272:ios:41fe4a0804f05d46c357d5',
    messagingSenderId: '561429560272',
    projectId: 'habbit-f077c',
    databaseURL: 'https://habbit-f077c-default-rtdb.firebaseio.com',
    storageBucket: 'habbit-f077c.appspot.com',
    iosClientId: '561429560272-sl70q422gvi1chiovb8frmigpup8cocf.apps.googleusercontent.com',
    iosBundleId: 'com.habbit',
  );
}
